# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  hello_world_job:
    runs-on: derek
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: ./
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number ${{ steps.foo.outputs.random-number }} 
      shell: bash
  release-please:
     runs-on: derek
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v2
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: node
           package-name: release-please-action
